/** Barnvänliga 16x16-föremål: hus, träd, sten, brunn, lykta, vegetation. */
import { PALETTE, paintPixels, drawSprite } from "./sprites.mjs";

export const HOUSE_KINDS = ["cottage", "hut", "barn", "tower", "cottage_round"];

export const DECOR_SPRITES = {
  cottage: [
    "................",
    ".....krrrrk.....",
    "....krrrrrrk....",
    "...krrwwrrrrk...",
    "..krrrrrrrrrrk..",
    ".krrrrrrrrrrrrk.",
    "kkkkkkkkkkkkkkkk",
    ".kuuuuuuuuuuuuk.",
    ".kuwukuuuuuwuuk.",
    ".kuuukuuuuuuuuk.",
    ".kuuuuuuuuuuuuk.",
    ".kuuuuukkkkuuuk.",
    ".kuuuuukyykuuuk.",
    ".kkkkkkkkkkkkkk.",
    "................",
    "................",
  ],
  hut: [
    "................",
    ".......kk.......",
    "......kuuk......",
    ".....kuuuuk.....",
    "....kuuuuuuk....",
    "...kuuwwuuuuk...",
    "..kuuuuuuuuuuk..",
    ".kkkkkkkkkkkkkk.",
    "..kuwukuuuwuuk..",
    "..kuuukuuuuuuk..",
    "..kuuuuuyyuuuk..",
    "..kkkkkkkkkkkk..",
    "................",
    "................",
    "................",
    "................",
  ],
  barn: [
    "................",
    "................",
    ".koooooooooook.",
    "koooooooooooook",
    "kkkkkkkkkkkkkkkk",
    ".kuuuuuuuuuuuuk.",
    ".kuwukuwwukwuuk.",
    ".kuuukuuuukuuuk.",
    ".kuuuuuuuuuuuuk.",
    ".kukkkkkkkkkukk.",
    ".kuuuuuyyyuuuuk.",
    ".kkkkkkkkkkkkkk.",
    "................",
    "................",
    "................",
    "................",
  ],
  tower: [
    "......kttk......",
    ".....ktwwtk.....",
    ".....kttttk.....",
    "....ktcccc tk...".replace(" ", "t"),
    "....ktcwwctk....",
    "....ktcccctk....",
    "....ktcccc tk...".replace(" ", "t"),
    "....kttttttk....",
    "....ktuuuutk....",
    "....ktuyyutk....",
    "....ktuuuutk....",
    "....kttttttk....",
    "...kkttttttkk...",
    "................",
    "................",
    "................",
  ],
  cottage_round: [
    "................",
    ".....kmmmmk.....",
    "....kmmwwmmk....",
    "...kmmmmmmmmk...",
    "..kmmmmmmmmmmk..",
    ".kkkkkkkkkkkkkk.",
    ".kuuuuuuuuuuuuk.",
    ".kuwukuuuuwuuuk.",
    ".kuuukuuuuuuuuk.",
    ".kuuuuuuyyuuuuk.",
    ".kkkkkkkkkkkkkk.",
    "................",
    "................",
    "................",
    "................",
    "................",
  ],
  tree: [
    "................",
    "....kddddddk....",
    "...kdaaaaawdk...",
    "..kdaawaaaadk...",
    ".kdaaaaaaaaadk..",
    ".kdalaaaalaadk..",
    ".kdaaaaaaaaadk..",
    "..kdaaaaaaadk...",
    "...kdaaaaddk....",
    "....kkukkkk.....",
    ".....kuuuk......",
    ".....kuuuk......",
    "....kuuuuuk.....",
    "...kuuuuuuuk....",
    "................",
    "................",
  ],
  bush: [
    "................",
    "................",
    "....kdadddk.....",
    "...kdaaaaadk....",
    "..kdalaaaaldk...",
    "..kdaawaaardk...",
    ".kdalaaaaaldk...",
    ".kdaaaaaaaadk...",
    "..kdaaaaaadk....",
    "...kddddddk.....",
    "....kuuukk......",
    "................",
    "................",
    "................",
    "................",
    "................",
  ],
  bush2: [
    "................",
    "...kllaaallk....",
    "..kllallalllk...",
    ".kllaaawaaallk..",
    ".kllallmllallk..",
    "kllaaaaaaaaallk.",
    ".kllaaalaaallk..",
    "..kllllllllk....",
    "...kddddddk.....",
    "....kuuuk.......",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
  ],
  fern: [
    "................",
    "......kak.......",
    ".....kaak.......",
    "....kalaak......",
    "...kaa.aaak.....",
    "..kalakaalak....",
    ".kaaa.k.aaak....",
    "..kakkaakak.....",
    "....kkaakk......",
    ".....kuuk.......",
    ".....kuuk.......",
    "................",
    "................",
    "................",
    "................",
    "................",
  ],
  tallgrass: [
    "................",
    "................",
    ".a...a.l..a.....",
    "aa..la.l.aa.l...",
    "la.lal.l.al.a...",
    "al.ala.a.la.l...",
    "la.lal.l.al.a...",
    "d..d.d.d..d.d...",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
  ],
  rock: [
    "................",
    "................",
    "................",
    ".....kiiiik.....",
    "....kiwwwiiik...",
    "...kiiiiiiiiik..",
    "...kiiiiiixiik..",
    "...kixiiiiiiik..",
    "....kiiiiiiik...",
    ".....kkkkkkk....",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
  ],
  well: [
    "................",
    "....kiiiiiik....",
    "...kiwwcccwik...",
    "...kiccccccik...",
    "...kicvvvvvik...",
    "...kiccccccik...",
    "...kiiiiiiiik...",
    "....kuxxxuk.....",
    "....kuuuuuk.....",
    ".....kkkkk......",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
  ],
  sign: [
    "................",
    "....kuuuuuk.....",
    "...kuyyyyyuk....",
    "...kuywyywyk....",
    "...kuyyyyyuk....",
    "....kuuuuuk.....",
    "......kuuk......",
    "......kuuk......",
    "......kuuk......",
    "......kuuk......",
    ".....kuuuuk.....",
    "................",
    "................",
    "................",
    "................",
    "................",
  ],
  lantern: [
    "................",
    "......kkk.......",
    "......kik.......",
    ".....kyyyk......",
    "....kygggyk.....",
    "....kygwggyk....",
    "....kygggyk.....",
    ".....kyyyk......",
    "......kuk.......",
    "......kuk.......",
    ".....kuuuk......",
    "................",
    "................",
    "................",
    "................",
    "................",
  ],
  crate: [
    "................",
    "................",
    "...kuuuuuuuk....",
    "...kuyyyyyuk....",
    "...kuygggyuk....",
    "...kuyyyyyuk....",
    "...kuuuuuuuk....",
    "...kukkkkkuk....",
    "...kuuuuuuuk....",
    "....kkkkkkk.....",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
  ],
  flower: [
    "................",
    "................",
    "......kmk.......",
    ".....kmwmk......",
    "....kmmmmmkk....",
    ".....kmwmk......",
    "......kak.......",
    ".....kaak.......",
    "....kalaak......",
    ".....kaak.......",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
  ],
};

export const DECOR_SCALE = {
  cottage: 5,
  hut: 3,
  barn: 6,
  tower: 7,
  cottage_round: 4,
  tree: 4,
  bush: 3,
  bush2: 3,
  fern: 3,
  tallgrass: 3,
  rock: 3,
  well: 3,
  sign: 3,
  lantern: 3,
  crate: 3,
  chest: 3,
  column: 3,
  flower: 2,
};

const SWAY = new Set(["tree", "bush", "bush2", "fern", "tallgrass", "flower"]);

export function validateDecor() {
  for (const [name, rows] of Object.entries(DECOR_SPRITES)) {
    const w = rows[0].length;
    if (rows.length !== 16 || w !== 16) throw new Error(`${name} inte 16x16 (${rows.length}x${w})`);
    for (const row of rows) {
      if (row.length !== w) throw new Error(`ojämn rad i ${name}: ${row.length} ${row}`);
      for (const ch of row) {
        if (!(ch in PALETTE)) throw new Error(`färg ${ch} i ${name}`);
      }
    }
  }
  return Object.keys(DECOR_SPRITES);
}

export function drawDecor(ctx, kind, cx, cy, scale = 3, timeMs = 0) {
  const rows = DECOR_SPRITES[kind];
  if (!rows) {
    drawSprite(ctx, kind, cx, cy, { scale, shadow: true });
    return;
  }
  const w = 16 * scale;
  const h = 16 * scale;
  const sway = SWAY.has(kind) ? Math.sin(timeMs / 280 + cx * 0.02) * (kind === "tree" ? 2.2 : 1.4) : 0;
  const x = Math.round(cx - w / 2 + sway);
  const y = Math.round(cy - h / 2);
  ctx.fillStyle = "rgba(0,0,0,0.22)";
  ctx.beginPath();
  ctx.ellipse(cx, cy + h * 0.36, w * 0.3, h * 0.1, 0, 0, Math.PI * 2);
  ctx.fill();
  paintPixels(ctx, rows, x, y, scale);
}
